AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'Rakefile'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

# Naming
Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

# Bundler
Bundler/OrderedGems:
  Enabled: false
